-- -------------------------------------------------------------
--
-- Module: filter
-- Generated by MATLAB(R) 9.14 and Filter Design HDL Coder 3.1.13.
-- Generated on: 2024-06-11 11:14:15
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- TestBenchStimulus: impulse step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(15 DOWNTO 0); -- sfix16_En15
         filter_out                      :   OUT   std_logic_vector(34 DOWNTO 0)  -- sfix35_En33
         );

END filter;


----------------------------------------------------------------
--Module Architecture: filter
----------------------------------------------------------------
ARCHITECTURE rtl OF filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(15 DOWNTO 0); -- sfix16_En15
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(-66, 16); -- sfix16_En18
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(-90, 16); -- sfix16_En18
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(-144, 16); -- sfix16_En18
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(-212, 16); -- sfix16_En18
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(-293, 16); -- sfix16_En18
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(-384, 16); -- sfix16_En18
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(-479, 16); -- sfix16_En18
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(-568, 16); -- sfix16_En18
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(-642, 16); -- sfix16_En18
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(-686, 16); -- sfix16_En18
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(-684, 16); -- sfix16_En18
  CONSTANT coeff12                        : signed(15 DOWNTO 0) := to_signed(-618, 16); -- sfix16_En18
  CONSTANT coeff13                        : signed(15 DOWNTO 0) := to_signed(-471, 16); -- sfix16_En18
  CONSTANT coeff14                        : signed(15 DOWNTO 0) := to_signed(-224, 16); -- sfix16_En18
  CONSTANT coeff15                        : signed(15 DOWNTO 0) := to_signed(140, 16); -- sfix16_En18
  CONSTANT coeff16                        : signed(15 DOWNTO 0) := to_signed(635, 16); -- sfix16_En18
  CONSTANT coeff17                        : signed(15 DOWNTO 0) := to_signed(1272, 16); -- sfix16_En18
  CONSTANT coeff18                        : signed(15 DOWNTO 0) := to_signed(2054, 16); -- sfix16_En18
  CONSTANT coeff19                        : signed(15 DOWNTO 0) := to_signed(2982, 16); -- sfix16_En18
  CONSTANT coeff20                        : signed(15 DOWNTO 0) := to_signed(4048, 16); -- sfix16_En18
  CONSTANT coeff21                        : signed(15 DOWNTO 0) := to_signed(5236, 16); -- sfix16_En18
  CONSTANT coeff22                        : signed(15 DOWNTO 0) := to_signed(6525, 16); -- sfix16_En18
  CONSTANT coeff23                        : signed(15 DOWNTO 0) := to_signed(7885, 16); -- sfix16_En18
  CONSTANT coeff24                        : signed(15 DOWNTO 0) := to_signed(9281, 16); -- sfix16_En18
  CONSTANT coeff25                        : signed(15 DOWNTO 0) := to_signed(10674, 16); -- sfix16_En18
  CONSTANT coeff26                        : signed(15 DOWNTO 0) := to_signed(12021, 16); -- sfix16_En18
  CONSTANT coeff27                        : signed(15 DOWNTO 0) := to_signed(13280, 16); -- sfix16_En18
  CONSTANT coeff28                        : signed(15 DOWNTO 0) := to_signed(14406, 16); -- sfix16_En18
  CONSTANT coeff29                        : signed(15 DOWNTO 0) := to_signed(15361, 16); -- sfix16_En18
  CONSTANT coeff30                        : signed(15 DOWNTO 0) := to_signed(16110, 16); -- sfix16_En18
  CONSTANT coeff31                        : signed(15 DOWNTO 0) := to_signed(16625, 16); -- sfix16_En18
  CONSTANT coeff32                        : signed(15 DOWNTO 0) := to_signed(16888, 16); -- sfix16_En18
  CONSTANT coeff33                        : signed(15 DOWNTO 0) := to_signed(16888, 16); -- sfix16_En18
  CONSTANT coeff34                        : signed(15 DOWNTO 0) := to_signed(16625, 16); -- sfix16_En18
  CONSTANT coeff35                        : signed(15 DOWNTO 0) := to_signed(16110, 16); -- sfix16_En18
  CONSTANT coeff36                        : signed(15 DOWNTO 0) := to_signed(15361, 16); -- sfix16_En18
  CONSTANT coeff37                        : signed(15 DOWNTO 0) := to_signed(14406, 16); -- sfix16_En18
  CONSTANT coeff38                        : signed(15 DOWNTO 0) := to_signed(13280, 16); -- sfix16_En18
  CONSTANT coeff39                        : signed(15 DOWNTO 0) := to_signed(12021, 16); -- sfix16_En18
  CONSTANT coeff40                        : signed(15 DOWNTO 0) := to_signed(10674, 16); -- sfix16_En18
  CONSTANT coeff41                        : signed(15 DOWNTO 0) := to_signed(9281, 16); -- sfix16_En18
  CONSTANT coeff42                        : signed(15 DOWNTO 0) := to_signed(7885, 16); -- sfix16_En18
  CONSTANT coeff43                        : signed(15 DOWNTO 0) := to_signed(6525, 16); -- sfix16_En18
  CONSTANT coeff44                        : signed(15 DOWNTO 0) := to_signed(5236, 16); -- sfix16_En18
  CONSTANT coeff45                        : signed(15 DOWNTO 0) := to_signed(4048, 16); -- sfix16_En18
  CONSTANT coeff46                        : signed(15 DOWNTO 0) := to_signed(2982, 16); -- sfix16_En18
  CONSTANT coeff47                        : signed(15 DOWNTO 0) := to_signed(2054, 16); -- sfix16_En18
  CONSTANT coeff48                        : signed(15 DOWNTO 0) := to_signed(1272, 16); -- sfix16_En18
  CONSTANT coeff49                        : signed(15 DOWNTO 0) := to_signed(635, 16); -- sfix16_En18
  CONSTANT coeff50                        : signed(15 DOWNTO 0) := to_signed(140, 16); -- sfix16_En18
  CONSTANT coeff51                        : signed(15 DOWNTO 0) := to_signed(-224, 16); -- sfix16_En18
  CONSTANT coeff52                        : signed(15 DOWNTO 0) := to_signed(-471, 16); -- sfix16_En18
  CONSTANT coeff53                        : signed(15 DOWNTO 0) := to_signed(-618, 16); -- sfix16_En18
  CONSTANT coeff54                        : signed(15 DOWNTO 0) := to_signed(-684, 16); -- sfix16_En18
  CONSTANT coeff55                        : signed(15 DOWNTO 0) := to_signed(-686, 16); -- sfix16_En18
  CONSTANT coeff56                        : signed(15 DOWNTO 0) := to_signed(-642, 16); -- sfix16_En18
  CONSTANT coeff57                        : signed(15 DOWNTO 0) := to_signed(-568, 16); -- sfix16_En18
  CONSTANT coeff58                        : signed(15 DOWNTO 0) := to_signed(-479, 16); -- sfix16_En18
  CONSTANT coeff59                        : signed(15 DOWNTO 0) := to_signed(-384, 16); -- sfix16_En18
  CONSTANT coeff60                        : signed(15 DOWNTO 0) := to_signed(-293, 16); -- sfix16_En18
  CONSTANT coeff61                        : signed(15 DOWNTO 0) := to_signed(-212, 16); -- sfix16_En18
  CONSTANT coeff62                        : signed(15 DOWNTO 0) := to_signed(-144, 16); -- sfix16_En18
  CONSTANT coeff63                        : signed(15 DOWNTO 0) := to_signed(-90, 16); -- sfix16_En18
  CONSTANT coeff64                        : signed(15 DOWNTO 0) := to_signed(-66, 16); -- sfix16_En18

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 63); -- sfix16_En15
  SIGNAL product64                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp                         : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product63                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_1                       : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product62                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_2                       : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product61                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_3                       : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product60                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_4                       : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product59                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_5                       : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product58                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_6                       : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product57                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_7                       : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product56                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_8                       : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product55                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_9                       : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product54                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_10                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product53                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_11                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product52                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_12                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product51                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_13                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product50                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_14                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product49                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_15                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product48                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_16                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product47                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_17                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product46                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_18                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product45                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_19                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product44                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_20                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product43                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_21                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product42                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_22                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product41                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_23                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product40                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_24                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product39                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_25                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product38                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_26                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product37                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_27                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product36                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_28                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product35                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_29                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product34                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_30                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product33                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_31                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product32                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_32                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product31                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_33                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product30                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_34                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product29                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_35                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product28                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_36                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product27                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_37                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product26                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_38                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product25                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_39                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product24                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_40                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product23                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_41                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product22                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_42                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product21                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_43                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product20                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_44                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product19                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_45                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product18                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_46                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product17                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_47                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product16                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_48                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product15                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_49                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product14                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_50                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product13                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_51                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product12                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_52                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product11                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_53                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product10                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_54                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product9                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_55                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product8                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_56                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product7                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_57                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product6                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_58                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product5                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_59                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product4                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_60                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product3                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_61                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product2                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_62                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL product1_cast                    : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL product1                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_63                      : signed(31 DOWNTO 0); -- sfix32_En33
  SIGNAL sum1                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp                         : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum2                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_1                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum3                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_2                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum4                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_3                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum5                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_4                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum6                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_5                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum7                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_6                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum8                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_7                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum9                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_8                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum10                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_9                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum11                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_10                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum12                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_11                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum13                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_12                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum14                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_13                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum15                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_14                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum16                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_15                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum17                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_16                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum18                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_17                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum19                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_18                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum20                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_19                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum21                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_20                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum22                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_21                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum23                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_22                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum24                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_23                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum25                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_24                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum26                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_25                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum27                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_26                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum28                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_27                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum29                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_28                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum30                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_29                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum31                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_30                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum32                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_31                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum33                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_32                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum34                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_33                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum35                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_34                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum36                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_35                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum37                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_36                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum38                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_37                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum39                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_38                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum40                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_39                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum41                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_40                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum42                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_41                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum43                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_42                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum44                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_43                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum45                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_44                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum46                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_45                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum47                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_46                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum48                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_47                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum49                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_48                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum50                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_49                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum51                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_50                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum52                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_51                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum53                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_52                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum54                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_53                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum55                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_54                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum56                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_55                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum57                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_56                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum58                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_57                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum59                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_58                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum60                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_59                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum61                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_60                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum62                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_61                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum63                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_62                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL output_typeconvert               : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL output_register                  : signed(34 DOWNTO 0); -- sfix35_En33


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 63) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 63) <= delay_pipeline(0 TO 62);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(63) * coeff64;
  product64 <= mul_temp(30 DOWNTO 0);

  mul_temp_1 <= delay_pipeline(62) * coeff63;
  product63 <= mul_temp_1(30 DOWNTO 0);

  mul_temp_2 <= delay_pipeline(61) * coeff62;
  product62 <= mul_temp_2(30 DOWNTO 0);

  mul_temp_3 <= delay_pipeline(60) * coeff61;
  product61 <= mul_temp_3(30 DOWNTO 0);

  mul_temp_4 <= delay_pipeline(59) * coeff60;
  product60 <= mul_temp_4(30 DOWNTO 0);

  mul_temp_5 <= delay_pipeline(58) * coeff59;
  product59 <= mul_temp_5(30 DOWNTO 0);

  mul_temp_6 <= delay_pipeline(57) * coeff58;
  product58 <= mul_temp_6(30 DOWNTO 0);

  mul_temp_7 <= delay_pipeline(56) * coeff57;
  product57 <= mul_temp_7(30 DOWNTO 0);

  mul_temp_8 <= delay_pipeline(55) * coeff56;
  product56 <= mul_temp_8(30 DOWNTO 0);

  mul_temp_9 <= delay_pipeline(54) * coeff55;
  product55 <= mul_temp_9(30 DOWNTO 0);

  mul_temp_10 <= delay_pipeline(53) * coeff54;
  product54 <= mul_temp_10(30 DOWNTO 0);

  mul_temp_11 <= delay_pipeline(52) * coeff53;
  product53 <= mul_temp_11(30 DOWNTO 0);

  mul_temp_12 <= delay_pipeline(51) * coeff52;
  product52 <= mul_temp_12(30 DOWNTO 0);

  mul_temp_13 <= delay_pipeline(50) * coeff51;
  product51 <= mul_temp_13(30 DOWNTO 0);

  mul_temp_14 <= delay_pipeline(49) * coeff50;
  product50 <= mul_temp_14(30 DOWNTO 0);

  mul_temp_15 <= delay_pipeline(48) * coeff49;
  product49 <= mul_temp_15(30 DOWNTO 0);

  mul_temp_16 <= delay_pipeline(47) * coeff48;
  product48 <= mul_temp_16(30 DOWNTO 0);

  mul_temp_17 <= delay_pipeline(46) * coeff47;
  product47 <= mul_temp_17(30 DOWNTO 0);

  mul_temp_18 <= delay_pipeline(45) * coeff46;
  product46 <= mul_temp_18(30 DOWNTO 0);

  mul_temp_19 <= delay_pipeline(44) * coeff45;
  product45 <= mul_temp_19(30 DOWNTO 0);

  mul_temp_20 <= delay_pipeline(43) * coeff44;
  product44 <= mul_temp_20(30 DOWNTO 0);

  mul_temp_21 <= delay_pipeline(42) * coeff43;
  product43 <= mul_temp_21(30 DOWNTO 0);

  mul_temp_22 <= delay_pipeline(41) * coeff42;
  product42 <= mul_temp_22(30 DOWNTO 0);

  mul_temp_23 <= delay_pipeline(40) * coeff41;
  product41 <= mul_temp_23(30 DOWNTO 0);

  mul_temp_24 <= delay_pipeline(39) * coeff40;
  product40 <= mul_temp_24(30 DOWNTO 0);

  mul_temp_25 <= delay_pipeline(38) * coeff39;
  product39 <= mul_temp_25(30 DOWNTO 0);

  mul_temp_26 <= delay_pipeline(37) * coeff38;
  product38 <= mul_temp_26(30 DOWNTO 0);

  mul_temp_27 <= delay_pipeline(36) * coeff37;
  product37 <= mul_temp_27(30 DOWNTO 0);

  mul_temp_28 <= delay_pipeline(35) * coeff36;
  product36 <= mul_temp_28(30 DOWNTO 0);

  mul_temp_29 <= delay_pipeline(34) * coeff35;
  product35 <= mul_temp_29(30 DOWNTO 0);

  mul_temp_30 <= delay_pipeline(33) * coeff34;
  product34 <= mul_temp_30(30 DOWNTO 0);

  mul_temp_31 <= delay_pipeline(32) * coeff33;
  product33 <= mul_temp_31(30 DOWNTO 0);

  mul_temp_32 <= delay_pipeline(31) * coeff32;
  product32 <= mul_temp_32(30 DOWNTO 0);

  mul_temp_33 <= delay_pipeline(30) * coeff31;
  product31 <= mul_temp_33(30 DOWNTO 0);

  mul_temp_34 <= delay_pipeline(29) * coeff30;
  product30 <= mul_temp_34(30 DOWNTO 0);

  mul_temp_35 <= delay_pipeline(28) * coeff29;
  product29 <= mul_temp_35(30 DOWNTO 0);

  mul_temp_36 <= delay_pipeline(27) * coeff28;
  product28 <= mul_temp_36(30 DOWNTO 0);

  mul_temp_37 <= delay_pipeline(26) * coeff27;
  product27 <= mul_temp_37(30 DOWNTO 0);

  mul_temp_38 <= delay_pipeline(25) * coeff26;
  product26 <= mul_temp_38(30 DOWNTO 0);

  mul_temp_39 <= delay_pipeline(24) * coeff25;
  product25 <= mul_temp_39(30 DOWNTO 0);

  mul_temp_40 <= delay_pipeline(23) * coeff24;
  product24 <= mul_temp_40(30 DOWNTO 0);

  mul_temp_41 <= delay_pipeline(22) * coeff23;
  product23 <= mul_temp_41(30 DOWNTO 0);

  mul_temp_42 <= delay_pipeline(21) * coeff22;
  product22 <= mul_temp_42(30 DOWNTO 0);

  mul_temp_43 <= delay_pipeline(20) * coeff21;
  product21 <= mul_temp_43(30 DOWNTO 0);

  mul_temp_44 <= delay_pipeline(19) * coeff20;
  product20 <= mul_temp_44(30 DOWNTO 0);

  mul_temp_45 <= delay_pipeline(18) * coeff19;
  product19 <= mul_temp_45(30 DOWNTO 0);

  mul_temp_46 <= delay_pipeline(17) * coeff18;
  product18 <= mul_temp_46(30 DOWNTO 0);

  mul_temp_47 <= delay_pipeline(16) * coeff17;
  product17 <= mul_temp_47(30 DOWNTO 0);

  mul_temp_48 <= delay_pipeline(15) * coeff16;
  product16 <= mul_temp_48(30 DOWNTO 0);

  mul_temp_49 <= delay_pipeline(14) * coeff15;
  product15 <= mul_temp_49(30 DOWNTO 0);

  mul_temp_50 <= delay_pipeline(13) * coeff14;
  product14 <= mul_temp_50(30 DOWNTO 0);

  mul_temp_51 <= delay_pipeline(12) * coeff13;
  product13 <= mul_temp_51(30 DOWNTO 0);

  mul_temp_52 <= delay_pipeline(11) * coeff12;
  product12 <= mul_temp_52(30 DOWNTO 0);

  mul_temp_53 <= delay_pipeline(10) * coeff11;
  product11 <= mul_temp_53(30 DOWNTO 0);

  mul_temp_54 <= delay_pipeline(9) * coeff10;
  product10 <= mul_temp_54(30 DOWNTO 0);

  mul_temp_55 <= delay_pipeline(8) * coeff9;
  product9 <= mul_temp_55(30 DOWNTO 0);

  mul_temp_56 <= delay_pipeline(7) * coeff8;
  product8 <= mul_temp_56(30 DOWNTO 0);

  mul_temp_57 <= delay_pipeline(6) * coeff7;
  product7 <= mul_temp_57(30 DOWNTO 0);

  mul_temp_58 <= delay_pipeline(5) * coeff6;
  product6 <= mul_temp_58(30 DOWNTO 0);

  mul_temp_59 <= delay_pipeline(4) * coeff5;
  product5 <= mul_temp_59(30 DOWNTO 0);

  mul_temp_60 <= delay_pipeline(3) * coeff4;
  product4 <= mul_temp_60(30 DOWNTO 0);

  mul_temp_61 <= delay_pipeline(2) * coeff3;
  product3 <= mul_temp_61(30 DOWNTO 0);

  mul_temp_62 <= delay_pipeline(1) * coeff2;
  product2 <= mul_temp_62(30 DOWNTO 0);

  product1_cast <= resize(product1, 35);

  mul_temp_63 <= delay_pipeline(0) * coeff1;
  product1 <= mul_temp_63(30 DOWNTO 0);

  add_temp <= resize(product1_cast, 36) + resize(product2, 36);
  sum1 <= add_temp(34 DOWNTO 0);

  add_temp_1 <= resize(sum1, 36) + resize(product3, 36);
  sum2 <= add_temp_1(34 DOWNTO 0);

  add_temp_2 <= resize(sum2, 36) + resize(product4, 36);
  sum3 <= add_temp_2(34 DOWNTO 0);

  add_temp_3 <= resize(sum3, 36) + resize(product5, 36);
  sum4 <= add_temp_3(34 DOWNTO 0);

  add_temp_4 <= resize(sum4, 36) + resize(product6, 36);
  sum5 <= add_temp_4(34 DOWNTO 0);

  add_temp_5 <= resize(sum5, 36) + resize(product7, 36);
  sum6 <= add_temp_5(34 DOWNTO 0);

  add_temp_6 <= resize(sum6, 36) + resize(product8, 36);
  sum7 <= add_temp_6(34 DOWNTO 0);

  add_temp_7 <= resize(sum7, 36) + resize(product9, 36);
  sum8 <= add_temp_7(34 DOWNTO 0);

  add_temp_8 <= resize(sum8, 36) + resize(product10, 36);
  sum9 <= add_temp_8(34 DOWNTO 0);

  add_temp_9 <= resize(sum9, 36) + resize(product11, 36);
  sum10 <= add_temp_9(34 DOWNTO 0);

  add_temp_10 <= resize(sum10, 36) + resize(product12, 36);
  sum11 <= add_temp_10(34 DOWNTO 0);

  add_temp_11 <= resize(sum11, 36) + resize(product13, 36);
  sum12 <= add_temp_11(34 DOWNTO 0);

  add_temp_12 <= resize(sum12, 36) + resize(product14, 36);
  sum13 <= add_temp_12(34 DOWNTO 0);

  add_temp_13 <= resize(sum13, 36) + resize(product15, 36);
  sum14 <= add_temp_13(34 DOWNTO 0);

  add_temp_14 <= resize(sum14, 36) + resize(product16, 36);
  sum15 <= add_temp_14(34 DOWNTO 0);

  add_temp_15 <= resize(sum15, 36) + resize(product17, 36);
  sum16 <= add_temp_15(34 DOWNTO 0);

  add_temp_16 <= resize(sum16, 36) + resize(product18, 36);
  sum17 <= add_temp_16(34 DOWNTO 0);

  add_temp_17 <= resize(sum17, 36) + resize(product19, 36);
  sum18 <= add_temp_17(34 DOWNTO 0);

  add_temp_18 <= resize(sum18, 36) + resize(product20, 36);
  sum19 <= add_temp_18(34 DOWNTO 0);

  add_temp_19 <= resize(sum19, 36) + resize(product21, 36);
  sum20 <= add_temp_19(34 DOWNTO 0);

  add_temp_20 <= resize(sum20, 36) + resize(product22, 36);
  sum21 <= add_temp_20(34 DOWNTO 0);

  add_temp_21 <= resize(sum21, 36) + resize(product23, 36);
  sum22 <= add_temp_21(34 DOWNTO 0);

  add_temp_22 <= resize(sum22, 36) + resize(product24, 36);
  sum23 <= add_temp_22(34 DOWNTO 0);

  add_temp_23 <= resize(sum23, 36) + resize(product25, 36);
  sum24 <= add_temp_23(34 DOWNTO 0);

  add_temp_24 <= resize(sum24, 36) + resize(product26, 36);
  sum25 <= add_temp_24(34 DOWNTO 0);

  add_temp_25 <= resize(sum25, 36) + resize(product27, 36);
  sum26 <= add_temp_25(34 DOWNTO 0);

  add_temp_26 <= resize(sum26, 36) + resize(product28, 36);
  sum27 <= add_temp_26(34 DOWNTO 0);

  add_temp_27 <= resize(sum27, 36) + resize(product29, 36);
  sum28 <= add_temp_27(34 DOWNTO 0);

  add_temp_28 <= resize(sum28, 36) + resize(product30, 36);
  sum29 <= add_temp_28(34 DOWNTO 0);

  add_temp_29 <= resize(sum29, 36) + resize(product31, 36);
  sum30 <= add_temp_29(34 DOWNTO 0);

  add_temp_30 <= resize(sum30, 36) + resize(product32, 36);
  sum31 <= add_temp_30(34 DOWNTO 0);

  add_temp_31 <= resize(sum31, 36) + resize(product33, 36);
  sum32 <= add_temp_31(34 DOWNTO 0);

  add_temp_32 <= resize(sum32, 36) + resize(product34, 36);
  sum33 <= add_temp_32(34 DOWNTO 0);

  add_temp_33 <= resize(sum33, 36) + resize(product35, 36);
  sum34 <= add_temp_33(34 DOWNTO 0);

  add_temp_34 <= resize(sum34, 36) + resize(product36, 36);
  sum35 <= add_temp_34(34 DOWNTO 0);

  add_temp_35 <= resize(sum35, 36) + resize(product37, 36);
  sum36 <= add_temp_35(34 DOWNTO 0);

  add_temp_36 <= resize(sum36, 36) + resize(product38, 36);
  sum37 <= add_temp_36(34 DOWNTO 0);

  add_temp_37 <= resize(sum37, 36) + resize(product39, 36);
  sum38 <= add_temp_37(34 DOWNTO 0);

  add_temp_38 <= resize(sum38, 36) + resize(product40, 36);
  sum39 <= add_temp_38(34 DOWNTO 0);

  add_temp_39 <= resize(sum39, 36) + resize(product41, 36);
  sum40 <= add_temp_39(34 DOWNTO 0);

  add_temp_40 <= resize(sum40, 36) + resize(product42, 36);
  sum41 <= add_temp_40(34 DOWNTO 0);

  add_temp_41 <= resize(sum41, 36) + resize(product43, 36);
  sum42 <= add_temp_41(34 DOWNTO 0);

  add_temp_42 <= resize(sum42, 36) + resize(product44, 36);
  sum43 <= add_temp_42(34 DOWNTO 0);

  add_temp_43 <= resize(sum43, 36) + resize(product45, 36);
  sum44 <= add_temp_43(34 DOWNTO 0);

  add_temp_44 <= resize(sum44, 36) + resize(product46, 36);
  sum45 <= add_temp_44(34 DOWNTO 0);

  add_temp_45 <= resize(sum45, 36) + resize(product47, 36);
  sum46 <= add_temp_45(34 DOWNTO 0);

  add_temp_46 <= resize(sum46, 36) + resize(product48, 36);
  sum47 <= add_temp_46(34 DOWNTO 0);

  add_temp_47 <= resize(sum47, 36) + resize(product49, 36);
  sum48 <= add_temp_47(34 DOWNTO 0);

  add_temp_48 <= resize(sum48, 36) + resize(product50, 36);
  sum49 <= add_temp_48(34 DOWNTO 0);

  add_temp_49 <= resize(sum49, 36) + resize(product51, 36);
  sum50 <= add_temp_49(34 DOWNTO 0);

  add_temp_50 <= resize(sum50, 36) + resize(product52, 36);
  sum51 <= add_temp_50(34 DOWNTO 0);

  add_temp_51 <= resize(sum51, 36) + resize(product53, 36);
  sum52 <= add_temp_51(34 DOWNTO 0);

  add_temp_52 <= resize(sum52, 36) + resize(product54, 36);
  sum53 <= add_temp_52(34 DOWNTO 0);

  add_temp_53 <= resize(sum53, 36) + resize(product55, 36);
  sum54 <= add_temp_53(34 DOWNTO 0);

  add_temp_54 <= resize(sum54, 36) + resize(product56, 36);
  sum55 <= add_temp_54(34 DOWNTO 0);

  add_temp_55 <= resize(sum55, 36) + resize(product57, 36);
  sum56 <= add_temp_55(34 DOWNTO 0);

  add_temp_56 <= resize(sum56, 36) + resize(product58, 36);
  sum57 <= add_temp_56(34 DOWNTO 0);

  add_temp_57 <= resize(sum57, 36) + resize(product59, 36);
  sum58 <= add_temp_57(34 DOWNTO 0);

  add_temp_58 <= resize(sum58, 36) + resize(product60, 36);
  sum59 <= add_temp_58(34 DOWNTO 0);

  add_temp_59 <= resize(sum59, 36) + resize(product61, 36);
  sum60 <= add_temp_59(34 DOWNTO 0);

  add_temp_60 <= resize(sum60, 36) + resize(product62, 36);
  sum61 <= add_temp_60(34 DOWNTO 0);

  add_temp_61 <= resize(sum61, 36) + resize(product63, 36);
  sum62 <= add_temp_61(34 DOWNTO 0);

  add_temp_62 <= resize(sum62, 36) + resize(product64, 36);
  sum63 <= add_temp_62(34 DOWNTO 0);

  output_typeconvert <= sum63;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
